version: '2'

services:

  bot:
    build: .
    command: python bot.py
    links:
      - db
      - redis
    volumes:
      - "./:/app"
    env_file:
      - './.env'

  celery:
    build: .
    command: celery -A tasks worker -B --loglevel=info 
    links:
      - db
    volumes:
      - "./:/app"
    env_file:
      - './.env'
    environment:
      - C_FORCE_ROOT=1

  db:
    image: mongo

  redis:
    image: redis
